# Generated by Django 2.1 on 2018-09-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('sub', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('linktext', models.CharField(max_length=200)),
                ('slot', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='IconCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slot', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('slot', models.CharField(max_length=2000)),
            ],
        ),
    ]
