# Generated by Django 2.1 on 2018-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.FileField(upload_to='hero_images/'),
        ),
    ]
