# Generated by Django 2.1 on 2018-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20180929_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='link',
            field=models.URLField(),
        ),
    ]
